# Configuration parameters
READ_BASE_PATH = '/mnt/storage/franklhtan/projects/LearnCsld2025/eval_outputs'
WRITE_BASE_PATH = '/mnt/storage/franklhtan/projects/LearnCsld2025/observe_outputs'
EPOCH_START = 10
EPOCH_END = 201
EPOCH_INTERVAL = 10
RUN_TIMES_START = 4
RUN_TIMES_END = 9
RUN_NAMES = ['NORM_BS32_LR1E4_F4_RCCL_CNN_ADAM', 'NORM_BS32_LR1E4_F4_RCCL_CNN_ADAM_FZ', 'NORM_BS32_LR1E4_F4_RCRC_CNN_ADAM', 'NORM_BS32_LR1E4_F4_RCRC_CNN_ADAM_FZ', 'NORM_BS32_LR1E4_F4_RCRC_CNN_ADAM_FC']
RUN_NAMES_SHORT = ["RCCL_NFZ", "RCCL_FZ", "RCRC_NFZ", "RCRC_FZ", "RCRC_CONT"]