_wandb:
    value:
        cli_version: 0.22.3
        e:
            y5h6f1b32y7wqklbwacjgagc271w806k:
                args:
                    - --config
                    - ./configs/T_0203_RCCL_PARA_FZ_1e5.py
                codePath: train_mix_ADAM_CNN_Norm_Single.py
                codePathLocal: train_mix_ADAM_CNN_Norm_Single.py
                cpu_count: 112
                cpu_count_logical: 224
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "67108864"
                        used: "12288"
                email: 460214560@qq.com
                executable: /opt/anaconda3/bin/python3
                gpu: NVIDIA RTX 6000 Ada Generation
                gpu_count: 9
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-44f30d49-59d3-850e-a668-e29aeafd13e5
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-06961186-6486-d2f7-7b5d-03ed458b8f4b
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-f14907c1-9e49-f6ba-c2e0-2e4b18717ebd
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-900877f8-1dc7-7b42-590a-3fbeacb48bd0
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-8ec063b7-fbc0-24eb-9dfb-8d89b18ad71a
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-c0d438a0-47d7-6e0c-d6ef-fc11e9f23b43
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-e3bca64d-f4ee-c0ee-3fe7-f1e9df1bcaef
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-843f9dae-98ec-ad1f-37c0-ec385febb929
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-038864d0-ee2a-0fdf-03f2-6fd07f644fb3
                host: atl01
                memory:
                    total: "270065917952"
                os: Linux-5.4.0-216-generic-x86_64-with-glibc2.35
                program: /mnt/storage/franklhtan/projects/LearnCsld2025/src/train_mix_ADAM_CNN_Norm_Single.py
                python: CPython 3.12.7
                root: /mnt/storage/franklhtan/projects/LearnCsld2025/src
                slurm:
                    cluster_name: atl
                    cpus_on_node: "2"
                    gtids: "0"
                    job_cpus_per_node: "2"
                    job_gid: "3006"
                    job_gpus: "1"
                    job_id: "1079"
                    job_name: 0203_rccl_para_fz_1e5
                    job_nodelist: atl01
                    job_num_nodes: "1"
                    job_partition: compute
                    job_uid: "3001"
                    job_user: franklhtan
                    jobid: "1079"
                    localid: "0"
                    mem_per_node: "16384"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: atl01
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /nfs/franklhtan/projects/LearnCsld2025/slurm_config
                    submit_host: Arts-Tech-Lab.Head
                    task_pid: "60168"
                    tasks_per_node: "1"
                    topology_addr: atl01
                    topology_addr_pattern: node
                    working_cluster: atl:Arts-Tech-Lab.Head:6817:8704:109
                startedAt: "2026-02-04T08:40:44.887863Z"
                writerId: y5h6f1b32y7wqklbwacjgagc271w806k
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
            "4": 3.12.7
            "5": 0.22.3
            "10":
                - 20
            "12": 0.22.3
            "13": linux-x86_64
